### ISSUE TITLE
Zimbra Administration - Storage Management: Your license for this feature has expired or is not valid

### ISSUE THREAD

**Issue by seaowl** [maldua/zimbra-foss#5]
With zcs-10.1.0_GA_4200000.UBUNTU20_64.20240719155625.tgz, fresh install.
Go Zimbra Administration (WebAdmin UI) > Home > Configure > Servers > Select server > Storage Management.
Got error:
> Your license for this feature has expired or is not valid.Please see Configure - Global Settings - License for more information.

The expected behavior is that a page displaying a list of message stores should open.

![zcs-10 1 0_GA_4200000 UBUNTU20_64 20240719155625 stores error](https://github.com/user-attachments/assets/a96488fd-f031-4fd5-86d8-dfa862eb478a)

**Comment by adriangibanelbtactic** [comment]
Thank you for your feedback.

I have created a [ZCS 10.1.0 Foss Build - [BUG] - ZimbraAdmin's Storage Management asks for license](https://forums.zimbra.org/viewtopic.php?t=72940) forum post to draw Synacor's attention so that they can fix it.

BTW I have also sent your screenshot hiding a bit better your Zimbra's FQDN ;) .

**Comment by adriangibanelbtactic** [comment]
Apparently this will be fixed in ZCS 10.1.1 thanks to this pull request: https://github.com/Zimbra/zm-admin-console/pull/174 .

Please reopen the bug or create a new one if the same problem arises in ZCS 10.1.1 build when it's available.

**Comment by adriangibanelbtactic** [comment]
Maldua's ZCS 10.1.1 is available to download.

Can you please check if the bug still happens in that version?

Thank you!

**Comment by adriangibanelbtactic** [comment]
Maldua's ZCS 10.1.2 is available to download.

Can you please check if the bug still happens in that version?

Thank you!

**Comment by adriangibanelbtactic** [comment]
I confirm this bug has been fixed in Maldua's ZCS 10.1.2 .
